import React, { Dispatch } from 'react'
import { GameState } from '../typings'

export const startingLocations: GameState['pieceLocations'] = {
  a1: { type: 'rook', color: 'white', inMoveMode: false },
  b1: { type: 'knight', color: 'white', inMoveMode: false },
  c1: { type: 'bishop', color: 'white', inMoveMode: false },
  d1: { type: 'queen', color: 'white', inMoveMode: false },
  e1: { type: 'king', color: 'white', inMoveMode: false },
  f1: { type: 'bishop', color: 'white', inMoveMode: false },
  g1: { type: 'knight', color: 'white', inMoveMode: false },
  h1: { type: 'rook', color: 'white', inMoveMode: false },
  a2: { type: 'pawn', color: 'white', inMoveMode: false },
  b2: { type: 'pawn', color: 'white', inMoveMode: false },
  c2: { type: 'pawn', color: 'white', inMoveMode: false },
  d2: { type: 'pawn', color: 'white', inMoveMode: false },
  e2: { type: 'pawn', color: 'white', inMoveMode: false },
  f2: { type: 'pawn', color: 'white', inMoveMode: false },
  g2: { type: 'pawn', color: 'white', inMoveMode: false },
  h2: { type: 'pawn', color: 'white', inMoveMode: false },
  a3: null,
  b3: null,
  c3: null,
  d3: null,
  e3: null,
  f3: null,
  g3: null,
  h3: null,
  a4: null,
  b4: null,
  c4: null,
  d4: null,
  e4: null,
  f4: null,
  g4: null,
  h4: null,
  a5: null,
  b5: null,
  c5: null,
  d5: null,
  e5: null,
  f5: null,
  g5: null,
  h5: null,
  a6: null,
  b6: null,
  c6: null,
  d6: null,
  e6: null,
  f6: null,
  g6: null,
  h6: null,
  a8: { type: 'rook', color: 'black', inMoveMode: false },
  b8: { type: 'knight', color: 'black', inMoveMode: false },
  c8: { type: 'bishop', color: 'black', inMoveMode: false },
  d8: { type: 'queen', color: 'black', inMoveMode: false },
  e8: { type: 'king', color: 'black', inMoveMode: false },
  f8: { type: 'bishop', color: 'black', inMoveMode: false },
  g8: { type: 'knight', color: 'black', inMoveMode: false },
  h8: { type: 'rook', color: 'black', inMoveMode: false },
  a7: { type: 'pawn', color: 'black', inMoveMode: false },
  b7: { type: 'pawn', color: 'black', inMoveMode: false },
  c7: { type: 'pawn', color: 'black', inMoveMode: false },
  d7: { type: 'pawn', color: 'black', inMoveMode: false },
  e7: { type: 'pawn', color: 'black', inMoveMode: false },
  f7: { type: 'pawn', color: 'black', inMoveMode: false },
  g7: { type: 'pawn', color: 'black', inMoveMode: false },
  h7: { type: 'pawn', color: 'black', inMoveMode: false },
}

export const GameStateContext = React.createContext<{
  state: GameState
  dispatch: Dispatch<{ type: string; payload: { moveFrom?: string; moveTo?: string } }>
}>({
  state: { globalMoveMode: false, pieceLocations: startingLocations },
  dispatch: () => null,
})
